name: Test SSH process

env:
  # share an ssh-agent socket across jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:

      - name: checkout this repo
        uses: actions/checkout@v2
        with:
          persists-credentials: false

      - name: SSH authentication from secrets
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # create an agent pointing at the shared socket > hiding output
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          # put the passphrase > into a file && make it executable
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          # pass the private key | sans carriage returns | to ssh-add, along with the password returned by the file > hiding output
          echo ${{ secrets.SSH_PRIVATE_KEY }} | tr -d '\r' | DISPLAY=NONE SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null
          # clean up file with passphrase
          rm ~/.ssh_askpass

      # debug step: print out the added identity
      - name: print ssh-add identities
        run: ssh-add -l

      # debug step: check we can push
      - name: push test to this repo
        run: |
          git remote set-url origin git@github.com:charlesfrye/actions-ssh-secrets.git
          echo "hello from inside the github action!" >> README.md
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A .
          git commit -m "testing SSH process"
          git push
